### ISSUE TITLE
Floww Tutorial Issue: Getting started (Ray/RLlib) Typo

### ISSUE THREAD

**Issue by mtgibson2014** [berkeleyflow/flow#28]
Under **Getting started (Ray/RLlib)** , it says:

_In order to test run an Flow experiment in RLlib, try the following command:
python examples/rllab/stabilizing_the_ring.py_

It should be: **python examples/rllib/stabilizing_the_ring.py**

**Comment by AboudyKreidieh** [comment]
resolved by #38
