### ISSUE TITLE
Sumo Setup Instructions

### ISSUE THREAD

**Issue by kjang96** [berkeleyflow/flow#5]
Setting up Sumo on OS X seems to require setting this `export CPPFLAGS=-I/opt/X11/include`  and `export LDFLAGS=-L/opt/X11/lib` before running `./configure`.  If it's not just me we should add this to the setup instructions?

**Comment by nskh** [comment]
I've had to do something like this too, but I don't think it happens to everyone... no idea why, though :/

**Comment by eugenevinitsky** [comment]
This happens to everyone and we should add it to the setup instructions. Good catch ya'll.

**Comment by nskh** [comment]
Addressed this in [PR #71](https://github.com/berkeleyflow/flow-devel/pull/71) on the `flow-devel` repo.

**Comment by eugenevinitsky** [comment]
Nice!

**Comment by cathywu** [comment]
Looks like this has been resolved, so closing this! Thanks @nskh !
