### ISSUE TITLE
Flow Setup (Mac & maybe others)

### ISSUE THREAD

**Issue by mtgibson2014** [berkeleyflow/flow#72]
Need to put a note in the setup instructions. 

Whenever I need to run the sumo-gui (or whenever the gui needs to be initialized), there's an error that states: FXApp::openDisplay: unable to open display :0.0 

In order to get the gui running, you need to open up Xquartz in your computer first and keep it running. Then, you can run the sumo/flow commands and run the simulations.

**Comment by eugenevinitsky** [comment]
Good catch.

**Comment by eugenevinitsky** [comment]
This is in now.

**Comment by RafalKucharskiPK** [comment]
doesn't work for me :/

I run xquartz (both from applications and from terminal)
both ways the error when i run sumo-gui from terminal and launchpad is still the same
